#! /usr/local/bin/php
<?php
require_once 'tutor.php';

if (isset($argv[1])) {
    $tutor = new Tutor();
    parse_str(implode('&', array_slice($argv, 1)), $_REQUEST);
    $_REQUEST['verbose'] = true;
    $tutor->handle_action();
}